from model.models import Task
from repository.repository import InMemoryTaskRepository


def test_should_add_item_with_autogenerated_id():
    in_memory_repository = InMemoryTaskRepository()

    task: Task = Task(id=0, title='Test', status='Todo')
    created_task: Task = in_memory_repository.create_task(task)

    assert created_task.id == 1


def test_should_get_item_by_id():
    in_memory_repository = InMemoryTaskRepository()
    in_memory_repository.create_task(Task(id=0, title='Test', status='Todo'))

    retrieved_task = in_memory_repository.get_task(1)
    assert retrieved_task.id == 1
    assert retrieved_task.title == 'Test'
    assert retrieved_task.status == 'Todo'


def test_should_not_get_item_by_id_when_not_present():
    in_memory_repository = InMemoryTaskRepository()

    retrieved_task = in_memory_repository.get_task(10)
    assert retrieved_task is None
